name: Environment Selection Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: envs
        options: 
        - qa
        - prod

jobs:
  greet:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - name: Set environment variables based on selection
      run: |
        ADDRESS=${{ vars.MAP_URL }}
        echo $ADDRESS
