name: Environment Selection Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: envs
        options: 
        - QA
        - PROD

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Check environment selection
      run: |
        echo "Selected environment: ${{ inputs.environment }}"

    - name: Set environment variables based on selection
      run: |
        KEYNAME="MAP_URL_${{ inputs.environment }}"
        ADDRESS=${{ vars["MAP_URL_QA"] }}
        echo $ADDRESS
        ADDRESS=${{ vars["MAP_URL_PROD"] }}
        echo $ADDRESS
